image: Visual Studio 2017

before_build:
  - nuget sources add -name myget.org -source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
  - nuget restore

configuration:
  - Release

environment:
  matrix:
  - solution_name: OpenHardwareMonitor.sln
build:
  project: '%solution_name%'
  verbosity: minimal

artifacts:
  - path: 'Bin\Release\'
